version: "2"

services:
  ota_api:
    image: 139.219.133.175:5000/tourbillon:v1.2.7
    container_name: ota_api
    ports:
      - 9001:9001
    environment:
      env_mode: prod
      HOSTNAME: tb-api-3
    volumes:
      - $PWD:/projects/tourbillon
      - /etc/localtime:/etc/localtime:ro
      - /etc/resolv.conf:/etc/resolv.conf
    restart: always
    privileged: true
    working_dir: /projects/tourbillon
    command: gunicorn 'run:create_app(tb_app_name="ota_api")' --bind 0.0.0.0:9001 -w 16 -k gevent  --max-requests 80000
