version: "2"

services:
  ota_api:
    image: 139.219.133.175:5000/tourbillon:v1.2.7
    container_name: ota_api
    ports:
      - 9001:9001
    environment:
      env_mode: test
      HOSTNAME: tb-api-test
    volumes:
      - $PWD:/projects/tourbillon
      - /etc/localtime:/etc/localtime:ro
      - /etc/resolv.conf:/etc/resolv.conf
    restart: always
    privileged: true
    working_dir: /projects/tourbillon
    command: gunicorn 'run:create_app(tb_app_name="ota_api")' --bind 0.0.0.0:9001 -w 1 -k gevent  --max-requests 80000

  flight_crawl_task:
    image: 139.219.133.175:5000/tourbillon:v1.2.7
    container_name: flight_crawl_task
    environment:
      env_mode: test
      HOSTNAME: tb-api-test
    volumes:
      - $PWD:/projects/tourbillon
      - /etc/localtime:/etc/localtime:ro
      - /etc/resolv.conf:/etc/resolv.conf
    restart: always
    privileged: true
    working_dir: /projects/tourbillon
    command: python run.py -t flight_crawl_task flight_crawl_task 1 1

  flight_ota_fare_task:
    image: 139.219.133.175:5000/tourbillon:v1.2.7
    container_name: flight_ota_fare_task
    environment:
      env_mode: test
      HOSTNAME: tb-api-test
    volumes:
    - $PWD:/projects/tourbillon
    - /etc/localtime:/etc/localtime:ro
    - /etc/resolv.conf:/etc/resolv.conf
    restart: always
    privileged: true
    working_dir: /projects/tourbillon
    command: python run.py -t flight_ota_fare_task flight_ota_fare_task 1 1

  dynamic_fare_task:
    image: 139.219.133.175:5000/tourbillon:v1.2.7
    container_name: dynamic_fare_task
    environment:
      env_mode: test
    volumes:
    - $PWD:/projects/tourbillon
    - /etc/localtime:/etc/localtime:ro
    - /etc/resolv.conf:/etc/resolv.conf
    restart: always
    privileged: true
    working_dir: /projects/tourbillon
    command: python run.py -t dynamic_fare_task dynamic_fare_task 1 1

  fare_comparison_task:
    image: 139.219.133.175:5000/tourbillon:v1.2.7
    container_name: fare_comparison_task
    environment:
      env_mode: test
      HOSTNAME: tb-api-test
    volumes:
    - $PWD:/projects/tourbillon
    - /etc/localtime:/etc/localtime:ro
    - /etc/resolv.conf:/etc/resolv.conf
    restart: always
    privileged: true
    working_dir: /projects/tourbillon
    command: python run.py -t fare_comparison_task fare_comparison_task 1 1

  crawler_manager:
      image: 139.219.133.175:5000/tourbillon:v1.2.7
      container_name: crawler_manager
      ports:
        - 8180:8180
      environment:
        env_mode: test
        HOSTNAME: tb-misc
      volumes:
        - $PWD:/projects/tourbillon
        - /etc/localtime:/etc/localtime:ro
        - /etc/resolv.conf:/etc/resolv.conf
      restart: always
      privileged: true
      working_dir: /projects/tourbillon
      command: python run.py -t crawler_manager crawler_manager

  order_manager:
    image: 139.219.133.175:5000/tourbillon:v1.2.7
    container_name: order_manager
    environment:
      env_mode: test
      HOSTNAME: tb-misc
    volumes:
      - $PWD:/projects/tourbillon
      - /etc/localtime:/etc/localtime:ro
      - /etc/resolv.conf:/etc/resolv.conf
    restart: always
    privileged: true
    working_dir: /projects/tourbillon
    command: python run.py -t order_manager order_manager

  sub_order_task:
    image: 139.219.133.175:5000/tourbillon:v1.2.7
    container_name: sub_order_task
    environment:
      env_mode: test
      HOSTNAME: tb-crawler-1
    volumes:
      - $PWD:/projects/tourbillon
      - /etc/localtime:/etc/localtime:ro
      - /etc/resolv.conf:/etc/resolv.conf
    restart: always
    privileged: true
    working_dir: /projects/tourbillon
    command: python run.py -t sub_order_task sub_order_task 1 1

  flight_order_task:
    image: 139.219.133.175:5000/tourbillon:v1.2.7
    container_name: flight_order_task
    environment:
      env_mode: test
      HOSTNAME: tb-crawler-1
    volumes:
      - $PWD:/projects/tourbillon
      - /etc/localtime:/etc/localtime:ro
      - /etc/resolv.conf:/etc/resolv.conf
    restart: always
    privileged: true
    working_dir: /projects/tourbillon
    command: python run.py -t flight_order_task flight_order_task 1 1
  web_api:
    image: 139.219.133.175:5000/tourbillon:v1.2.7
    container_name: web_api
    ports:
      - 9801:9801
    environment:
      env_mode: test
      HOSTNAME: tb-api-test
    volumes:
      - $PWD:/projects/tourbillon
      - /etc/localtime:/etc/localtime:ro
      - /etc/resolv.conf:/etc/resolv.conf
    restart: always
    privileged: true
    working_dir: /projects/tourbillon
    command: gunicorn 'run:create_app(tb_app_name="web_api")' --bind 0.0.0.0:9801 -w 8 -k gevent   --max-requests 10

  provider_api:
    image: 139.219.133.175:5000/tourbillon:v1.2.7
    container_name: provider_api
    ports:
      - 9501:9501
    environment:
      env_mode: test
      HOSTNAME: tb-api-test
    volumes:
      - $PWD:/projects/tourbillon
      - /etc/localtime:/etc/localtime:ro
      - /etc/resolv.conf:/etc/resolv.conf
    restart: always
    privileged: true
    working_dir: /projects/tourbillon
    command: gunicorn 'run:create_app(tb_app_name="provider_api")' --bind 0.0.0.0:9501 -w 8 -k gevent   --max-requests 10

#  lowprice_stabilizer:
#    image: 139.219.133.175:5000/tourbillon:v1.2.6
#    container_name: lowprice_stabilizer
#    environment:
#      env_mode: test
#      HOSTNAME: tb-api-test
#    volumes:
#      - $PWD:/projects/tourbillon
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/resolv.conf:/etc/resolv.conf
#    restart: always
#    privileged: true
#    working_dir: /projects/tourbillon
#    command: python run.py -t lowprice_stabilizer lowprice_stabiliz

  web_frontend:
    image: nginx:1.12-alpine
    container_name: web_frontend
    ports:
      - 9802:9802
    environment:
      env_mode: test
      HOSTNAME: tb-api-test
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/app/web_frontend/dist:/projects/tourbillon/app/web_frontend/dist
      - $PWD/app/web_frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/resolv.conf:/etc/resolv.conf
    restart: always
    privileged: true
    working_dir: /projects/tourbill

  misc_task:
    image: 139.219.133.175:5000/tourbillon:v1.2.7
    container_name: misc_task
    environment:
      env_mode: test
      HOSTNAME: tb-api-test
    volumes:
      - $PWD:/projects/tourbillon
      - /etc/localtime:/etc/localtime:ro
      - /etc/resolv.conf:/etc/resolv.conf
    restart: always
    privileged: true
    working_dir: /projects/tourbillon
    command: python run.py -t misc_task misc_task

  scheduled_airline_crawl_task:
    image: 139.219.133.175:5000/tourbillon:v1.2.7
    container_name: scheduled_airline_crawl_task
    environment:
      env_mode: test
      HOSTNAME: tb-api-test
    volumes:
    - $PWD:/projects/tourbillon
    - /etc/localtime:/etc/localtime:ro
    - /etc/resolv.conf:/etc/resolv.conf
    restart: always
    privileged: true
    working_dir: /projects/tourbillon
    command: python run.py -t scheduled_airline_crawl_task scheduled_airline_crawl_task 1 1